"""empty message

Revision ID: 0475000fba38
Revises: 9f746fd1dd67
Create Date: 2020-07-21 15:18:17.914882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0475000fba38'
down_revision = '9f746fd1dd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tf_summary_logs',
    sa.Column('uuid', sa.Text(), nullable=False),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tf_summary_logs')
    # ### end Alembic commands ###
