"""empty message

Revision ID: 250e1e9f3fe2
Revises: 0475000fba38
Create Date: 2020-12-28 14:52:03.611048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250e1e9f3fe2'
down_revision = '0475000fba38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('session_closed_at', sa.Integer(), nullable=True))
    op.add_column('commits', sa.Column('session_started_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commits', 'session_started_at')
    op.drop_column('commits', 'session_closed_at')
    # ### end Alembic commands ###
