"""empty message

Revision ID: 5bd2e2c3d74f
Revises: 9fa5fb7a9f65
Create Date: 2020-05-25 13:26:44.364867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd2e2c3d74f'
down_revision = '9fa5fb7a9f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('color', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'color')
    # ### end Alembic commands ###
