"""empty message

Revision ID: 7ae8c2333da0
Revises: e2614146a0af
Create Date: 2020-06-04 13:18:38.974816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae8c2333da0'
down_revision = 'e2614146a0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executables', sa.Column('interpreter_path', sa.Text(), nullable=True))
    op.add_column('executables', sa.Column('script_path', sa.Text(), nullable=True))
    op.add_column('executables', sa.Column('working_dir', sa.Text(), nullable=True))
    op.drop_column('executables', 'command')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executables', sa.Column('command', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('executables', 'working_dir')
    op.drop_column('executables', 'script_path')
    op.drop_column('executables', 'interpreter_path')
    # ### end Alembic commands ###
