"""empty message

Revision ID: 895b3e907405
Revises: 5fa91e4a8741
Create Date: 2020-06-13 12:47:07.050620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895b3e907405'
down_revision = '5fa91e4a8741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commit_tag', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit_tag', sa.Column('uuid', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
