"""empty message

Revision ID: 9f746fd1dd67
Revises: e4c2561d5f16
Create Date: 2020-07-06 19:27:22.281548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f746fd1dd67'
down_revision = 'e4c2561d5f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executables', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executables', 'is_hidden')
    # ### end Alembic commands ###
