"""empty message

Revision ID: a2a0a52d90f3
Revises: 895b3e907405
Create Date: 2020-06-22 10:50:28.642900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a0a52d90f3'
down_revision = '895b3e907405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('experiment_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commits', 'experiment_name')
    # ### end Alembic commands ###
