"""empty message

Revision ID: d92be5728b36
Revises: 250e1e9f3fe2
Create Date: 2021-01-11 09:43:42.967646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92be5728b36'
down_revision = '250e1e9f3fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'commits', ['experiment_name', 'hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commits', type_='unique')
    # ### end Alembic commands ###
