"""empty message

Revision ID: e4c2561d5f16
Revises: a2a0a52d90f3
Create Date: 2020-06-30 18:35:35.627856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c2561d5f16'
down_revision = 'a2a0a52d90f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'is_hidden')
    # ### end Alembic commands ###
